logging:
  level:
    com.anarodriguez: debug

csv:
  location: '/home/anita/Downloads/licenses.csv'

mongodb:
      db: licenses
      username: root
      password: example
      host: 127.0.0.1
      port: 27017
      authSource: admin